name: Readme Update

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install ChromeDriver
      run: |
        DOWNLOAD_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64").url') \
          && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "$DOWNLOAD_URL" \
          && cd /tmp \
          && unzip -q -o -j chromedriver_linux64.zip \
          && rm -rf chromedriver_linux64.zip \
          && sudo mv chromedriver /usr/local/bin/chromedriver \
          && sudo chmod +x /usr/local/bin/chromedriver \
          && chromedriver --version --no-sandbox
    - name: Update README
      run: ./bin/run
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit README.md -m 'Update README' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
